### PR TITLE
One more fix to multi method translate

### PR DESCRIPTION
**Pull request by vrurg**
FCO/Red#145

### CODE REVIEW

**Comment by FCO** [comment]
That way `:gambi` would be required... I didn't get why this should be required...

**Comment by FCO** [comment]
and that's breaking the tests...

**Comment by vrurg** [comment]
Otherwise translate from `Pg` driver doesn't get called from iterator's `TWEAK`. There is either a bug in rakudo or I miss something in how multidispatch works. Neither I understand how come role's candidate override the one from consuming class, but this is what happens.

It's hard for me to check with tests because they were failing for me in first place. If I get time later today I'll open a new issue and create a code snippet for this.

**Comment by vrurg** [comment]
Hm, so far I can't extract the essence of the problem with the dispatch. Here is the stack trace I receive on my real-life code:

```
Earlier failures:
 (HANDLED) Dynamic variable $*bind-counter not found
  in method wildcard at /Users/vrurg/src/Perl6/BO-Trading/../Red/lib/Red/Driver/Pg.pm6 (Red::Driver::Pg) line 29
  in method translate at /Users/vrurg/src/Perl6/BO-Trading/../Red/lib/Red/Driver/CommonSQL.pm6 (Red::Driver::CommonSQL) line 259
  in method translate at /Users/vrurg/src/Perl6/BO-Trading/../Red/lib/Red/Driver/CommonSQL.pm6 (Red::Driver::CommonSQL) line 152
  in submethod TWEAK at /Users/vrurg/src/Perl6/BO-Trading/../Red/lib/Red/ResultSeq/Iterator.pm6 (Red::ResultSeq::Iterator) line 12
  in method iterator at /Users/vrurg/src/Perl6/BO-Trading/../Red/lib/Red/ResultSeq.pm6 (Red::ResultSeq) line 65
  in block <unit> at t/20-db-salestax.t6 line 45
```

I'll be doing my best to reproduce it in a short version.

**Comment by vrurg** [comment]
Ok, got it, finally.

```
$*RED-DB.execute('DROP TABLE IF EXISTS my_model CASCADE');
$*RED-DB.execute('DROP TABLE IF EXISTS my_model_rel CASCADE');

model MyModelRel {...}

model MyModel {
    has Int $.id is serial;
    has Str $.data is column;
    has MyModelRel $.parent is relationship{ .child-id };
    has MyModelRel @.children is relationship{ .parent-id };
}

model MyModelRel {
    has Int $.id is serial;
    has Int $.parent-id is referencing{ MyModel.id };
    has Int $.child-id is referencing{ MyModel.id }
    has MyModel $.parent is relationship{ .parent-id };
    has MyModel $.child is relationship{ .child-id };
}

MyModel.^create-table;
MyModelRel.^create-table;

for <line1 line2 line3> -> $data {
    MyModel.^create: :$data;
}

my $l1 = MyModel.^find: data => 'line1';

for <a b c d> -> $suff {
    my $lc = MyModel.^create: data => "line1$suff";
    MyModelRel.^create: parent-id => $l1.id, child-id => $lc.id;
}

say MyModel.^find( data => 'line1' ).children.map( { .child.data } ).List.join(",");
```

The final line generates the stack trace.

**Comment by vrurg** [comment]
I think #154 is better. Closing this one.

**Pull request closed without merging**
