### PR TITLE
Private phasers

### PR DESCRIPTION
**Pull request by vrurg**
Pretty nice especially if applying a specialized role to a model. Then there is no need to reveal to the public a thing like:

```
method !remove-record-from-cache is before-delete is before-update {
    ...
}
```

### CODE REVIEW

**Comment by FCO** [comment]
@vrurg It's breaking the tests... :(

**Comment by vrurg** [comment]
> Who am I to ask for that, but would you mind to add some tests for it?

Add a smile to this phrase or else I'm feeling embarassed! ;)

Ok, I'll do as soon as I get time for it. I wonder what could be wrong with travis here because there is nothing in the patch that would conflict with the release.

**Comment by vrurg** [comment]
Added tests, as requested.

**Comment by FCO** [comment]
>Added tests, as requested.

@vrurg thank you very much! But it seems there are something odd: 
https://travis-ci.org/FCO/Red/builds/567677498?utm_source=github_status&utm_medium=notification

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vrurg** [comment]
Tried all my best to reproduce the problem with tests, but without success. Perhaps it'd make sense to run an individual test in the container to get more detailed output.

**Comment by FCO** [comment]
My branch that is a copy of your PR is passing... it it's still not passing here... Idk what to do... https://travis-ci.org/FCO/Red/builds/604221184?utm_source=github_status&utm_medium=notification

**Comment by vrurg** [comment]
So, the problem was in old version of rakudo where `.^private_methods` wasn't implemented. I have switched to a bit more clunky `.^private_method_table.values` which is a hash of methods and now test failures are consistent with those on your master.

Probably, it's ready for merge.

**Comment by vrurg** [comment]
And, BTW, it seems that Red is simply not compatible with old rakudo. But considering its complexity and reliance of properly fixed compiler I think it should be fine to require a recent rakudo implementation.

**Comment by FCO** [comment]
\o/
Thank you very much!

**Pull request merged**
