### PR TITLE
Make it possible to use a map with more than one column... Fixes #44

### LINKED ISSUE #44: Make map accept return more than one column

### PR DESCRIPTION
**Pull request by FCO**
@jonathanstowe would you mind to test it with your code? it is possible that this breaks the models on different files feature... :(

Thank you!

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Sure. Just at London Bridge Station at the moment so in an hour or so 😎

**Comment by FCO** [comment]
In 9 days I’ll be there too! :)

**Comment by FCO** [comment]
Thanks!

**Comment by jonathanstowe** [comment]
Well it definitely hasn't broken anything :+1:   So I'd so it was good to go.

**Comment by FCO** [comment]
Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
