### PR TITLE
Implement IN in generated SQL

### PR DESCRIPTION
**Pull request by jonathanstowe**
This implements an 'in', '⊂', '(<)' operators for IN and '⊃' and '(>)'
for 'NOT IN' (also allowing negation of IN).

The ResultSeq on the RHS doesn't quite work without being made into an
AST as it appears to expand the result in the operator subroutine,

This mostly implements https://github.com/FCO/Red/issues/87

### CODE REVIEW

**Comment by jonathanstowe** [comment]
For some reason I can't quite work out,  even with the ResultSeq candidate it selects the Positional candidate and executes the query to expand to the results.  It works but doesn't do what one expects (that is you don't get a sub-query, but two separate queries.)

**Comment by FCO** [comment]
have you tried to add a `is default` on the ResultSeq candidate?

**Comment by jonathanstowe** [comment]
I have now and it doesn't seem to make any difference.

**Comment by FCO** [comment]
:(

**Comment by jonathanstowe** [comment]
Oh wait I've got it,  just needed a different type constraint and not use a @ sigilled parameter.  Let me add that to the tests and I'll push it.

**Comment by jonathanstowe** [comment]
Gah, there's actually another problem which I didn't notice because I was only using one model in the tests.

With something like:

```perl6
use Red;

model Bar {
    has Int $.id is serial;
    has Str $.name is column;
}

model Foo {
    has Int $.id is serial;
    has Str $.name is column;
    has Int $.bar-id is referencing({ Bar.id } );
    has Bar $.bar is relationship( { .bar-id });
}

my $*RED-DEBUG          = $_ with %*ENV<RED_DEBUG>;
my $*RED-DB             = database "SQLite", |(:database($_) with %*ENV<RED_DATABASE>);

Bar.^create-table;
Foo.^create-table;


my @bars;

for <one two three four> -> $name {
    @bars.append: Bar.^create(:$name);
}

for @bars -> $bar {
    Foo.^create(:$bar, name => $bar.name ~ '-foo');
}

say Foo.^rs.grep(*.bar-id in Bar.^rs.grep( *.name eq 'one' ).map( *.id ) );
#say Foo.^rs.grep(*.bar-id in (1, 2) );

```

It ends up bringing in the Bar into the outer query so  it gets:

```sql
SELECT
   foo.bar_id as "bar-id", foo.id , foo.name 
FROM
   foo,
   bar
WHERE
   foo.bar_id IN ( SELECT
      bar.id as "data_1"
   FROM
      bar
   WHERE
      bar.name = 'one'	 )
```

Which is clearly less than awesome.  Let me find how that is happening.

**Comment by FCO** [comment]
I think you'll have to make `.tables` do not return what's inside the `in` clause

**Comment by jonathanstowe** [comment]
Fixed that in a way that  might be more useful in the future.

**Comment by jonathanstowe** [comment]
Right that should be it, the last one was just to hide the implementation detail lest we might want to create a new AST class for sub-selects in the future.

**Comment by FCO** [comment]
Thanks!

**Pull request merged**
