### PR TITLE
Fix for crash on unique constraint violation error

### PR DESCRIPTION
**Pull request by vrurg**
issue #166

### CODE REVIEW

**Comment by FCO** [comment]
@vrurg I as testing it now, and it couldn't find the `message-detail` method... Are we using different versions of Db::Pg?

```
MBP-de-Fernando:Red fernando$ perl6 -I.  -MRed -e '


model Bla is table<issue_166> { has Int $.id is id }

my $*RED-DB = database "Pg";

Bla.^create-table: :if-not-exists;

Bla.^create(:1id) for ^2;

'
No such method 'message-detail' for invocant of type 'DB::Pg::Error::FatalError'
  in method map-exception at /Users/fernando/Documents/Projects/Red/lib/Red/Driver/Pg.pm6 (Red::Driver::Pg) line 114
  in block  at /Users/fernando/Documents/Projects/Red/lib/Red/Statement.pm6 (Red::Statement) line 14
  in any  at /Users/fernando/Documents/Projects/Red/lib/Red/Statement.pm6 (Red::Statement) line 12
  in any  at /Users/fernando/Documents/Projects/Red/.precomp/C2D649C18CBEF01CF6223D4D25870642F9D5F94A/34/34BB07DEE8AFD9738074A43AA369FB6754BAC94A line 1
  in block  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 27
  in any  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 22
  in method error-check at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/BF0AB823535437669BD65E45A12568DBAF41E52E (DB::Pg::Database) line 124
  in method execute at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 18
  in method stt-exec at /Users/fernando/Documents/Projects/Red/lib/Red/Driver/Pg.pm6 (Red::Driver::Pg) line 82
  in method execute at /Users/fernando/Documents/Projects/Red/lib/Red/Driver.pm6 (Red::Driver) line 38
  in method save at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 246
  in method create at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 295
  in block <unit> at -e line 10
```

**Comment by FCO** [comment]
For me, master gives the right error:

```
MBP-de-Fernando:Red fernando$ perl6 -I.  -MRed -e '


model Bla is table<issue_166> { has Int $.id is id }

my $*RED-DB = database "Pg";

Bla.^create-table: :if-not-exists;

Bla.^create(:1id) for ^2;

'
Unique constraint (id) violated
Original error:
ERROR:  duplicate key value violates unique constraint "issue_166_pkey"
DETAIL:  Key (id)=(1) already exists.

  in block  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 27
  in any  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 22
  in method error-check at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/BF0AB823535437669BD65E45A12568DBAF41E52E (DB::Pg::Database) line 124
  in method execute at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 18
  in method stt-exec at /Users/fernando/Documents/Projects/Red/lib/Red/Driver/Pg.pm6 (Red::Driver::Pg) line 82
  in method execute at /Users/fernando/Documents/Projects/Red/lib/Red/Driver.pm6 (Red::Driver) line 38
  in method save at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 246
  in method create at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 295
  in block <unit> at -e line 10

Actually thrown at:
  in block  at /Users/fernando/Documents/Projects/Red/lib/Red/Statement.pm6 (Red::Statement) line 14
  in any  at /Users/fernando/Documents/Projects/Red/lib/Red/Statement.pm6 (Red::Statement) line 12
  in any  at /Users/fernando/Documents/Projects/Red/.precomp/C2D649C18CBEF01CF6223D4D25870642F9D5F94A/34/34BB07DEE8AFD9738074A43AA369FB6754BAC94A line 1
  in block  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 27
  in any  at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 22
  in method error-check at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/BF0AB823535437669BD65E45A12568DBAF41E52E (DB::Pg::Database) line 124
  in method execute at /Users/fernando/.rakudobrew/moar-master/install/share/perl6/site/sources/34BB07DEE8AFD9738074A43AA369FB6754BAC94A (DB::Pg::Statement) line 18
  in method stt-exec at /Users/fernando/Documents/Projects/Red/lib/Red/Driver/Pg.pm6 (Red::Driver::Pg) line 82
  in method execute at /Users/fernando/Documents/Projects/Red/lib/Red/Driver.pm6 (Red::Driver) line 38
  in method save at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 246
  in method create at /Users/fernando/Documents/Projects/Red/lib/MetamodelX/Red/Model.pm6 (MetamodelX::Red::Model) line 295
  in block <unit> at -e line 10

```

**Comment by vrurg** [comment]
I finally got time to reply. ;) I have `DB::Pg:ver<0.6>` installed. Checked against the repo and found the attribute in `DB::Pg::Native`.

**Comment by FCO** [comment]
I've updated my DB::Pg and now my Red::Driver::Pg is broken...

**Comment by FCO** [comment]
Thank you!

**Pull request merged**
