### PR TITLE
Collection of small fixes in the red CLI, SQL parsing, model generation, and test warnings

### PR DESCRIPTION
**Pull request by japhb**
This is a collection of small fixes (often single lines) in various places, mostly having to do with using the `red` CLI for parsing SQL schemas and generating model code.  I also fixed one set of test warnings and commented the location of another (for the benefit of the next person looking at it).

### CODE REVIEW

**Comment by japhb** [comment]
I have no idea what to do with that check failure -- it seems to have failed while trying to welcome me to the project ...?  What even?

**Comment by FCO** [comment]
Thank you very much! I'll take a look at it tomorrow, ok?
Thank you!

**Comment by FCO** [comment]
I couldn't wait for it... I merged it from my mobile anyway.

Thanks again!

**Comment by FCO** [comment]
It seems it have broken the tests... but I’ll need to leave that for tomorrow

**Comment by FCO** [comment]
Travis still passes

**Pull request merged**
