### PR TITLE
Reuse Pg connection on begin

### PR DESCRIPTION
**Pull request by FCO**

### CODE REVIEW

**Comment by jonathanstowe** [comment]
This will fall foul of the DB::Pg "connection pooling"  if the driver is shared between thread.  The 'BEGIN', 'COMMIT' and all the statements between *must* use the same native connection, so in the 8d47d9d2336e265315129ed0d60d953422dda117 I made it so the `new-connection`  get a Driver with a different `DB::Pg` which is a cheat assuming that the transaction will all be on the same thread and thus get the same native connection from the pool.  If the same DB::Pg is used in the transaction then there is a chance that some other thread will get the original native connection (on which the 'BEGIN' was issued,) from the pool and the statements that follow (and assumed to be in the transaction,) will get a new connection which is not actually in the transaction.

The only other way of doing this would be  not to put the native connection back in the pool while in a transaction (that is not call  `$db.finish` after the statements in the transaction.)

**Comment by jonathanstowe** [comment]
See e.g. #503 #504

**Comment by jonathanstowe** [comment]
`DB::Pg` handles the transactions itself by having the `begin`, `commit` and `rollback` methods on the `DB::Pg::Database` - so an alternative would be to arrange to use the same `DB::Pg::Database` (obtained once from `$!dbh.db` ) for all the `execute` in the transaction.

**Comment by FCO** [comment]
Ok... I've forgotten about that...

The problem I was trying to fix is: some simple like `Model.^create xx 100` is breaking because of too many connections.

**Comment by FCO** [comment]
What if we call $!dbh.begin on Red::Driver::Pg.begin? Its return will be used for the whole transaction, right?

**Comment by jonathanstowe** [comment]
> The problem I was trying to fix is: some simple like `Model.^create xx 100` is breaking because of too many connections.

Ah, that would be fixed by calling `$!dbh.finish`  when we're finished with the Driver created for the transaction (i.e. in the `rollback` or `commit` .)  Or, from where the code is now, wrapping the whole thing in `red-do { .... }, :transaction` 

In the `DB::Pg`  one would do something like:

```raku

# $dbh is the DB::Pg object that Red has in the $!dbh

my $db = $dbh.db.begin;

$db.execute(....);
...
$db.commit.finish
```

Whereas in the `Red::Driver::Pg::Statement` there is:

```raku
        my $db = $stt.db;
        my $sth = $db.prepare($!query);
        my $s = $sth.execute(|(@bind or @!binds));
        $db.finish;
```

Which compromises the "single native connection per transaction" by retrieving the `.db` from the pool and then putting it back on the pool with the `.finish`; so really what should happen is that a `BEGIN` should retrieve the `DB::Pg::Database` (and not `.finish` it,) and that same `DB::Pg::Database` should be used for all the statements in transaction (without a `.finish`,) and finally the `COMMIT` or `ROLLBACK` should `.finish` the `DB::Pg::Database` and subsequent statements should get a new one from the pool.

The #504 was just a workaround as the above would need quite a lot of work.

**Comment by FCO** [comment]
@jonathanstowe what about now? (sorry, I've mixed it yo with some other small changes...)

**Comment by FCO** [comment]
My test is this:

```raku
use Test;
use Red;
use Red::Do;

model Upload {
    has UInt     $.id            is id is serial;
    has DateTime $.time          is column = DateTime.now;
    has          @.misalignments is relationship({ .upload-id }, model => "DailyMisalignment" );
}

model DailyMisalignment {
    has UInt $.id           is id is serial;
    has Str  $.name         is column;
    has UInt $.upload-id    is referencing(model => "Upload", column => "id" );
    has      $.upload       is relationship({ .upload-id }, model => 'Upload');

    has DateTime $.time is column = DateTime.now;
}

my $*RED-DB = database "Pg", dbname => "postgres";
my $*RED-DEBUG = so %*ENV<RED_DEBUG>;

Upload.^create-table:            :unless-exists;
DailyMisalignment.^create-table: :unless-exists;
DailyMisalignment.^delete; Upload.^delete;

await start { Upload.^create(:misalignments[{ :name<foo> }]) xx 100 } xx 10;

is Upload.^all.elems, 1000, "Created all 1000 rows";
is DailyMisalignment.^all.elems, 1000, "Created all 1000 rows";
```

and it's consistently creating all the rows.

**Comment by jonathanstowe** [comment]
It looks about right, and your test looks like it should flush out the original problem, but I'd like to test it full-up which will have to wait until the morning.

**Comment by FCO** [comment]
Thank you for all your help!

The test says RedX::HashedPassword is failing with this version, but I couldn't reproduce that locally...

Let's see if it will work tomorrow!

Thanks!

**Pull request merged**
